name: Self Host

on:
  workflow_dispatch:

jobs:
  build:
    name: Start Building...
    runs-on: ubuntu-latest
    steps:
      - name: Setup Coolify
        run: |
          curl -fsSL https://cdn.coollabs.io/coolify/install.sh | bash
