name: Self Host

on:
  workflow_dispatch:

jobs:
  build:
    name: Start Building...
    runs-on: ubuntu-latest
    steps:
      - name: Setup Coolify
        run: |
          sudo apt-get update && sudo apt-get install cloudflared
