name: Public IP

on:
 workflow_dispatch:

 # ${{ secrets.HST_TKN }}
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin' # Install OpenJDK from the AdoptOpenJDK distribution
        java-version: '17'
    
    - name: Verify Java version
      run: java -version

    - name: Run server
      run: java -Xmx1024M -Xms1024M -jar server.jar nogui
      working-directory: ./linux/ms_server/
