name: Test

on:
  push:
  workflow_dispatch:

jobs:
  build:
    name: Setup Machine
    runs-on: ubuntu-latest
    steps:

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.9 

      - name: Set up CF
        run: |
          ls
          sudo mkdir -p --mode=0755 /usr/share/keyrings
          curl -fsSL https://pkg.cloudflare.com/cloudflare-main.gpg | sudo tee /usr/share/keyrings/cloudflare-main.gpg >/dev/null
          echo "deb [signed-by=/usr/share/keyrings/cloudflare-main.gpg] https://pkg.cloudflare.com/cloudflared $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/cloudflared.list
           sudo apt-get update && sudo apt-get install cloudflared

      - name: Setup Service
        run: |
            sudo cloudflared service install ${{ secrets.CF_KEY }}

      - name: Run app
        run: |
            pip install flask
            python py/app.py
        # working-directory: ../py/
         
